### ISSUE TITLE
Problem producing distribution zip file

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster#761]
I'm following the ReleaseProcess on Debian 8:
```
$ git clone https://github.com/zonemaster/zonemaster-gui.git
$ cd zonemaster-gui
$ npm install
npm WARN package.json zonemaster-gui@3.0.1 No repository field.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-8-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/mattiasp/zonemaster-gui
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mattiasp/zonemaster-gui/npm-debug.log
npm ERR! not ok code 0
```
Attachment: [npm-debug.log](https://github.com/zonemaster/zonemaster/files/3152716/npm-debug.log)

**Comment by matsduf** [comment]
@pamasse, can you look at this?

If the description in section 8, "Produce distribution zip file", in [Release Processes] is incorrect or incomplete, the issue belongs here. Else, it should be moved to [Zonemaster-GUI].

[Zonemaster-GUI]: https://github.com/zonemaster/zonemaster-gui
[Release Processes]: https://github.com/zonemaster/zonemaster/blob/master/docs/internal-documentation/maintenance/ReleaseProcess.md#8-produce-distribution-zip-file-zonemaster-gui-only
